server:
  port: 9001
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/libMgnt_auth?useSSL=false
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: validate

  security:
    filter-order: 5
check-user-scopes: true


